# hyprlang noerror false
# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ##### Preset WindowRules #####
# Blur/Transparency Global:
# windowrule = opacity 0.89 override 0.89 override, no_blur off, match:class .*

# Blur/Transparency Whitelist:
# windowrule = opacity 0.89 override 0.89 override, no_blur off, match:class (?i).*(dolphin|code|kitty|spotify).*

# Blur/Transparency Blacklist:
# windowrule = opacity 1 override 1 override, no_blur on, match:class (?i).*(dolphin|code|kitty|spotify).*

# Disable Blur for XWayland (Compatibility):
# windowrule = no_blur on, match:xwayland 1

# ##### Custom WindowRules #####
# windowrule = float on, opacity 1 override, no_blur on, match:class steam, match:title negative:(?i).*steam.*
