# This script is meant to be sourced.
# It's not for directly running.

function prepare_systemd_user_service(){
  if [[ ! -e "/usr/lib/systemd/user/ydotool.service" ]]; then
    x sudo ln -s /usr/lib/systemd/{system,user}/ydotool.service
  fi
}

function setup_user_group(){
    if [[ "$OS_GROUP_ID" == "arch" ]]; then
      x sudo usermod -aG video,i2c,input "$(whoami)"
    fi
}

function install_silent_sddm_theme(){
  local tmp_dir
  tmp_dir="$(mktemp -d)"
  x git clone -b main --depth=1 https://github.com/uiriansan/SilentSDDM "$tmp_dir/SilentSDDM"
  x sudo bash -c "cd '$tmp_dir/SilentSDDM' && ./install.sh"
  x rm -rf "$tmp_dir"
}

function setup_sddm_theme_helper_sudoers(){
  local helper_path
  helper_path="$(realpath -m "$XDG_CONFIG_HOME/quickshell/ii/scripts/colors/sddm/sddm-set-theme.sh")"
  local sudoers_dest="/etc/sudoers.d/99-sddm-theme-helper"

  x sudo mkdir -p /etc/sudoers.d
  x sudo bash -c "cat > '$sudoers_dest' <<EOF
# Auto-generated by dots-hyprland installer
Cmnd_Alias SDDM_SET_THEME = $helper_path *
%wheel ALL=(root) NOPASSWD: SDDM_SET_THEME
%sudo  ALL=(root) NOPASSWD: SDDM_SET_THEME
EOF"
  x sudo chmod 0440 "$sudoers_dest"
  x sudo chown root:root "$sudoers_dest"
  if command -v visudo >/dev/null 2>&1; then
    x sudo visudo -cf "$sudoers_dest"
  fi
}

function setup_sddm_theming(){
  if ! command -v systemctl >/dev/null 2>&1; then
    printf "${STY_YELLOW}[$0]: systemd not detected; skipping SDDM setup.${STY_RST}\n"
    return 0
  fi
  install_silent_sddm_theme
  setup_sddm_theme_helper_sudoers
  x sudo systemctl enable sddm
}
#####################################################################################
# These python packages are installed using uv into the venv (virtual environment). Once the folder of the venv gets deleted, they are all gone cleanly. So it's considered as setups, not dependencies.
showfun install-python-packages
v install-python-packages

showfun setup_user_group
v setup_user_group

# Only run SDDM setup if SDDM is installed
if command -v sddm >/dev/null 2>&1 && [[ "${SKIP_SDDM:-false}" != "true" ]]; then
  showfun setup_sddm_theming
  v setup_sddm_theming
fi

if [[ ! -z $(systemctl --version) ]]; then
  # For Fedora, uinput is required for the virtual keyboard to function, and udev rules enable input group users to utilize it.
  if [[ "$OS_GROUP_ID" == "fedora" ]]; then
    v bash -c "echo uinput | sudo tee /etc/modules-load.d/uinput.conf"
    v bash -c 'echo SUBSYSTEM==\"misc\", KERNEL==\"uinput\", MODE=\"0660\", GROUP=\"input\" | sudo tee /etc/udev/rules.d/99-uinput.rules'
  else
    v bash -c "echo i2c-dev | sudo tee /etc/modules-load.d/i2c-dev.conf"
  fi
  # TODO: find a proper way for enable Nix installed ydotool. When running `systemctl --user enable ydotool, it errors "Failed to enable unit: Unit ydotool.service does not exist".
  if [[ ! "${INSTALL_VIA_NIX}" == true ]]; then
    if [[ "$OS_GROUP_ID" == "fedora" ]]; then
      v prepare_systemd_user_service
    fi
    # When $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR are empty, it commonly means that the current user has been logged in with `su - user` or `ssh user@hostname`. In such case `systemctl --user enable <service>` is not usable. It should be `sudo systemctl --machine=$(whoami)@.host --user enable <service>` instead.
    if [[ ! -z "${DBUS_SESSION_BUS_ADDRESS}" ]]; then
      v systemctl --user enable ydotool --now
    else
      v sudo systemctl --machine=$(whoami)@.host --user enable ydotool --now
    fi
  fi
  v sudo systemctl enable bluetooth --now
elif [[ ! -z $(openrc --version) ]]; then
  v bash -c "echo 'modules=i2c-dev' | sudo tee -a /etc/conf.d/modules"
  v sudo rc-update add modules boot
  v sudo rc-update add ydotool default
  v sudo rc-update add bluetooth default

  x sudo rc-service ydotool start
  x sudo rc-service bluetooth start
else
  printf "${STY_RED}"
  printf "====================INIT SYSTEM NOT FOUND====================\n"
  printf "${STY_RST}"
  pause
fi

if [[ "$OS_GROUP_ID" == "gentoo" ]]; then
  v sudo chown -R $(whoami):$(whoami) ~/.local/
fi

v gsettings set org.gnome.desktop.interface font-name 'Google Sans Flex Medium 11 @opsz=11,wght=500'
v gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
v kwriteconfig6 --file kdeglobals --group KDE --key widgetStyle Darkly
